[package]
name = "amp001-example"
version = "0.1.0"
edition = "2021"
default-run = "amp001-example"

[dependencies]
crypto_box = "0.9"
ed25519-dalek = { version = "2", features = ["rand_core"] }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"
