[package]
name = "amp002-004-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
amp001-example = { path = "../rust-amp001" }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"
